### ISSUE TITLE
In TowerEval-Data-v0.1, instructions_data/5_shot/mt/tico19.en-ru/instructions.txt appears to be a synthetic link

### ISSUE THREAD

**Issue by cherryc** [deep-spin/tower-eval#4]
Thanks for the great work!

Going through the files, `instructions_data/5_shot/mt/tico19.en-ru/instructions.txt` appears to be a synthetic link. All other instructions.txt files exist, but this one cannot be read.

**Comment by zeppombal** [comment]
Hi,

Thanks for spotting this. I think I've fixed; could you download the data again and confirm, please?

Small note: we're going to release a paper on Tower soon, and the test data will also be updated.

**Comment by cherryc** [comment]
Looks good, thank you!
